name: Running GitHub Labeler

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  label_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@f4f6b96e7e747b5416cd470f3cfecf26abaa811e # v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
